export const VideoModels = [
  {
    id: 1,
    name: "alaradirik/deforum-kandinsky-2-2",
    default_params: {
      fps: 24,
      seed: 17,
      steps: 80,
      width: 640,
      height: 640,
      scheduler: "euler_ancestral",
      animations: "live | right | right | right | live",
      max_frames: 72,
      prompt_durations: "0.6 | 0.3 | 1 | 0.3 | 0.8",
      animation_prompts:
        "winter forest, snowflakes, Van Gogh style | spring forest, flowers, sun rays, Van Gogh style | summer forest, lake, reflections on the water, summer sun, Van Gogh style | autumn forest, rain, Van Gogh style | winter forest, snowflakes, Van Gogh style",
    },
    version: "1900f6d4c445b31063abb39008af79687bf9f3a264cd9b0fcbb7da293a59dc76",
    source: "replicate",
    url: "https://pbxt.replicate.delivery/S5ufXV1otWWuWyAoBaeQzOuM2KL1VrHFKx3Oj4RyTl7GtCvRA/output_2_2.mp4",
  },
  {
    id: 2,
    name: "cjwbw/tokenflow",
    default_params: {
      fps: 20,
      video:
        "https://replicate.delivery/pbxt/KGcnUKDlfys2uAo8eHbWSE8Pzc17hI5IOGdstViaBvfPJWHY/wolf.mp4",
      width: 512,
      height: 512,
      n_frames: 40,
      guidance_scale: 8,
      diffusion_prompt: "a shiny silver robotic wolf",
      inversion_prompt: "",
      num_diffusion_steps: 50,
      num_inversion_steps: 50,
      negative_diffusion_prompt:
        "ugly, blurry, low res, unrealistic, unaesthetic",
    },
    version: "d456a26c0c1764ac4d9b933a564fe70e660c46423ba0afb5d3200f1a46060728",
    source: "replicate",
    description: "",
    url: "https://replicate.delivery/pbxt/1Z5jF8MGBw7DNhTSUj8YGSA48d6YsWzDFskNvb2guZZVo1jE/out.mp4",
  },
  {
    id: 3,
    name: "ali-vilab/i2vgen-xl",
    default_params: {
      image:
        "https://replicate.delivery/pbxt/KA6KcZp2UhselAqryBuWaIV2w3KPKYJpVM9cQtqSctlhwdK5/img_0002.png",
      prompt: "A blonde girl in jeans",
      max_frames: 16,
      guidance_scale: 9,
      num_inference_steps: 50,
    },
    version: "5821a338d00033abaaba89080a17eb8783d9a17ed710a6b4246a18e0900ccad4",
    source: "replicate",
    description: "",
    url: "https://replicate.delivery/pbxt/8FpYFhLD6XKYIpivyRjI3LHHhV4C1kAVsGZSP4f2f4Uk6NJSA/out.mp4",
  },
  {
    id: 4,
    name: "cjwbw/videocrafter",
    default_params: {
      task: "text2video",
      prompt:
        "A tiger walks in the forest, photorealistic, 4k, high definition",
      save_fps: 10,
      ddim_steps: 50,
      unconditional_guidance_scale: 12,
    },
    version: "99957f2369ee2916300e97390c10f642aafc8d7652c23ea55adf9d6f9bffb187",
    source: "replicate",
    description: "",
    url: "https://replicate.delivery/pbxt/Y6PY6xd42to6FJM9FWao0mBa5CJrV1LhZF9P9pZChWlNfj6IA/output.mp4",
  },
  {
    id: 5,
    name: "cjwbw/lavie",
    default_params: {
      width: 512,
      height: 320,
      prompt: "a Corgi walking in the park at sunrise, oil painting style",
      quality: 9,
      video_fps: 8,
      interpolation: false,
      sample_method: "ddpm",
      guidance_scale: 7,
      super_resolution: false,
      num_inference_steps: 50,
    },
    version: "0bca850c4928b6c30052541fa002f24cbb4b677259c461dd041d271ba9d3c517",
    source: "replicate",
    description: "",
    url: "https://replicate.delivery/pbxt/RXCtleF9AJTea0LIS32LREtQ2uWHxirA07X5LhENFqIXeU1jA/out.mp4",
  },
  {
    id: 6,
    name: "deforum/deforum_stable_diffusion",
    default_params: {
      fps: 15,
      zoom: "0: (1.04)",
      angle: "0:(0)",
      sampler: "klms",
      max_frames: 100,
      translation_x: "0: (0)",
      translation_y: "0: (0)",
      color_coherence: "Match Frame 0 LAB",
      animation_prompts:
        "a beautiful forest by Asher Brown Durand, trending on Artstation",
      seed: 0,
    },
    version: "e22e77495f2fb83c34d5fae2ad8ab63c0a87b6b573b6208e1535b23b89ea66d6",
    source: "replicate",
    description: "",
    url: "https://replicate.delivery/mgxm/873a1cc7-0427-4e8d-ab3c-02ef5282c377/out.mp4",
  },
  {
    id: 7,
    name: "andreasjansson/stable-diffusion-animation",
    default_params: {
      width: 512,
      height: 512,
      prompt_end:
        "tall rectangular black monolith, a white room in the future with a bed, victorian details and a tall black monolith, a detailed matte painting by Wes Anderson, behance, light and space, reimagined by industrial light and magic, matte painting, criterion collection",
      prompt_start:
        "tall rectangular black monolith, monkeys in the desert looking at a large tall monolith, a detailed matte painting by Wes Anderson, behance, light and space, reimagined by industrial light and magic, matte painting, criterion collection",
      gif_ping_pong: true,
      output_format: "mp4",
      guidance_scale: 9,
      prompt_strength: 0.9,
      film_interpolation: true,
      intermediate_output: false,
      num_inference_steps: 50,
      num_animation_frames: 25,
      gif_frames_per_second: 20,
      num_interpolation_steps: 5,
      seed: 0,
    },
    version: "ca1f5e306e5721e19c473e0d094e6603f0456fe759c10715fcd6c1b79242d4a5",
    source: "replicate",
    description: "",
    url: "https://replicate.delivery/mgxm/56df19d7-3776-4119-a0f9-d278b26a4a8a/output.mp4",
  },
  {
    id: 8,
    name: "arielreplicate/stable_diffusion_infinite_zoom",
    default_params: {
      prompt: "A path going into the woods",
      inpaint_iter: 2,
      output_format: "mp4",
    },
    version: "a2527c5074fc0cf9fa6015a40d75d080d1ddf7082fabe142f1ccd882c18fce61",
    source: "replicate",
    description: "",
    url: "https://replicate.delivery/pbxt/iPWPdknk7e1fkEECe8AhzVVE6lceedKnpx6JxIHkEswr0ofeHA/infinit_zoom.mp4",
  },
  {
    id: 9,
    name: "camenduru/animatediff-lightning-4-step",
    default_params: {
      prompt: "A girl smiling",
      guidance_scale: 1,
    },
    version: "be39c6d599942831314b770f03cfd062bfd0faa8cc52e9289bcce830b721fcb6",
    source: "replicate",
    description: "",
    url: "https://replicate.delivery/pbxt/6fXfbY7Rd0jsqktlFL3yPVwikAaNuVLm2WMBAJqFGnxYYkiSA/animation.mp4",
  },
];

export const ImageModels = [
  {
    id: 1,
    name: "camenduru/animatediff-lightning-4-step",
    default_params: {
      width: 1656,
      height: 744,
      prompt:
        "A cinematic film still of a (Movie Still) from Suicide Squad , (extremely intricate:1.3), (realistic), portrait of a girl, the most beautiful in the world, Margot Robbie as Harley Quinn, colorful hair, pigtails, blue eyes, baseball bat, teeth, (detailed face, detailed eyes, clear skin, clear eyes), photorealistic, award winning, professional photograph of a stunning woman detailed, sharp focus, dramatic, award winning, cinematic lighting, volumetrics dtx \n",
      num_images: 1,
      guidance_scale: 6,
      negative_prompt: "text, watermark, blur, deformed, noised",
      num_inference_steps: 30,
    },
    version: "be39c6d599942831314b770f03cfd062bfd0faa8cc52e9289bcce830b721fcb6",
    source: "replicate",
    description: "",
    url: "https://replicate.delivery/pbxt/dRfqIaXP7U1tLqAFOFHxeIr2HaksXqEM7uOfeqcEGDHDqbKKB/out-0.jpg",
  },
];
